### ISSUE TITLE
Case insensitive filter search

### ISSUE THREAD

**Issue by fredcallaway** [jnewland/alfred-open-windows#4]
I think the filter should be case-insensitive. I'm sure this is straightforward, but I don't know enough bash to know where in the pipeline this would go.

**Comment by DavidAwad** [comment]
I still want this and can't find anything on it.

**Comment by jnewland** [comment]
Should be fixed by https://github.com/jnewland/alfred-open-windows/issues/6.

**Comment by benvan** [comment]
Wow - merged before I could finish my comment here!

This is a great alfred extension @jnewland - thanks very much

**Comment by jnewland** [comment]
> This is a great alfred extension @jnewland - thanks very much

I'm glad it's useful! 🙇 Thanks for your contribution, @benvan! I've invited you to the repo as a contributor to make it easier for you to make any other improvements in the future. 😄
