### ISSUE TITLE
Does not work with Visual Studio Code

### ISSUE THREAD

**Issue by tituswoo** [jnewland/alfred-open-windows#5]
When I open multiple windows in Visual Studio Code, and it is the currently focused/active application, the workflow is unable to recognize that Code has any windows open at all. It is just blank, like this:

![image](https://cloud.githubusercontent.com/assets/5308669/22035247/1f57b222-dca4-11e6-9428-56470732535b.png)

Again thanks for this workflow. It's an absolute **gem**!! 😄  🎉

**Comment by jnewland** [comment]
Interesting! Does this applescript return a list of windows when run in the Applescript Editor?

```

set output to ""
set theapp to "/Applications/PATH TO VISUAL STUDIO CODE"
tell application theapp
	set mywindowlist to the name of every window whose visible is true
end tell


repeat with n in mywindowlist
	set output to output & n & return
end repeat
return output
```

**Comment by tituswoo** [comment]
Thanks for the quick reply! 😄 
This is what I'm getting:

![image](https://cloud.githubusercontent.com/assets/5308669/22077336/a166c9a0-dd68-11e6-8ab5-8b151d826b70.png)

**Comment by jnewland** [comment]
Hmm, that's interesting! The same applescript works fine with all other applications that I'm using, so I'm not sure how to address this problem offhand :/.

**Comment by nikitavoloboev** [comment]
Doesn't work for Visual Studio Code for me too. Perhaps it's because VS Code is an electron app and doesn't have an applescript dictionary. Is there any way to add support to it?

Love the workflow.

**Comment by jnewland** [comment]
Fixed in https://github.com/jnewland/alfred-open-windows/releases/tag/v0.0.1! ✨
